### ISSUE TITLE
dependency installation conflict

### ISSUE THREAD

**Issue by agn-7** [aminalaee/sqladmin#519]
During the installation of this package using `pip` I got the following error:

```
.
.
.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googletrans 3.0.0 requires httpx==0.13.3, but you have httpx 0.24.1 which is incompatible.
```

I think the `googletrans` PyPI package version is bounded into the `setup.py` which caused this error. But I couldn't find the `setup.py` to fix it.

**Comment by aminalaee** [comment]
Hey @agn-7 
I think the issue is that sqladmin requires starlette[full] and that requires httpx 22 or newer: https://github.com/encode/starlette/blob/2168e47052239da5df35d5353bb986f760c51cef/pyproject.toml#L41

Its interesting because I think I shouldn't have used starlette[full] here: https://github.com/aminalaee/sqladmin/blob/1940e545765c08c66ed284731d5e4e4d2077ce8b/pyproject.toml#L30
Because httpx is not required for sqladmin.

**Comment by aminalaee** [comment]
Feel free to update this in pypronect.toml

**Comment by agn-7** [comment]
Thank you for your instant response.

#520

**Comment by agn-7** [comment]
But apparently, the starlette[full] was needed as the test cases failed due to the required dependencies like `jinja` which was in the starlette full dependencies.
