### ISSUE TITLE
Support the Aiohttp framework

### ISSUE THREAD

**Issue by anorprogrammer** [aminalaee/sqladmin#714]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Hi there,

I think this project is really cool and it can use some [aiohttp](https://docs.aiohttp.org/en/stable/) support.

**Comment by hasansezertasan** [comment]
As far as I know, framework agnosticism is not a priority to SQLAdmin. I don't think it'll be done.

On the other hand, @cemrehancavdar recently did what you mentioned for Litestar:

[cemrehancavdar/sqladmin-litestar: SQLAlchemy Admin for Litestar (original is for FastAPI and Starlette)](https://github.com/cemrehancavdar/sqladmin-litestar)

You can do the same for aiohttp. I'm not familiar with aiohttp but as I remember it doesn't support ASGI/WSGI so the workflow might be different than what @cemrehancavdar did (since litestar is also an ASGI framework like FastAPI/Starlette).

**Comment by aminalaee** [comment]
I will close this in favor of @hasansezertasan 's repository.
